#!/bin/bash

# Let find the dynamic libraries needed by the testsuite for native_api testing
# and ADDRESS.testGroup
export DYLD_LIBRARY_PATH=$builder_build_dir/lib:$DYLD_LIBRARY_PATH
rexx testOORexx "$@"
