#!/bin/bash

if [ "$0" = "$BASH_SOURCE" ] ; then echo "Usage : source ${BASH_SOURCE[0]}" ; exit 1 ; fi

# Old build system (configure)
export CFLAGS="-O3 $CFLAGS"
export CXXFLAGS="-O3 $CXXFLAGS"

# New build system (cmake)
export CMAKE_BUILD_TYPE=Release
