#!/bin/bash

if [ "$0" = "$BASH_SOURCE" ] ; then echo "Usage : source ${BASH_SOURCE[0]}" ; exit 1 ; fi

# Those variables must be defined before calling this script
#if test -z "$builder_branch" ; then echo "builder_branch is undefined" ; return 1 ; fi   # Can be empty, don't test it
if test -z "$builder_build_dir" ; then echo "builder_build_dir is undefined" ; return 1 ; fi
if test -z "$builder_config" ; then echo "builder_config is undefined" ; return 1 ; fi
if test -z "$builder_config_dir" ; then echo "builder_config_dir is undefined" ; return 1 ; fi
if test -z "$builder_delivery_dir" ; then echo "builder_delivery_dir is undefined" ; return 1 ; fi
if test -z "$builder_local_dir" ; then echo "builder_local_dir is undefined" ; return 1 ; fi
if test -z "$builder_scripts_dir" ; then echo "builder_scripts_dir is undefined" ; return 1 ; fi
if test -z "$builder_shared_dir" ; then echo "builder_shared_dir is undefined" ; return 1 ; fi
if test -z "$builder_src_dir" ; then echo "builder_src_dir is undefined" ; return 1 ; fi
if test -z "$builder_src_relative_path" ; then echo "builder_src_relative_path is undefined" ; return 1 ; fi
if test -z "$builder_target" ; then echo "builder_target is undefined" ; return 1 ; fi

alias cdoorexx='cd $builder_shared_dir'
alias cdshared='cd $builder_shared_dir'
alias cdoorexxlocal='cd $builder_local_dir'
alias cdlocal='cd $builder_local_dir'

alias cdroot='cd $builder_shared_dir/$builder_target'
alias cdofficial='cd $builder_shared_dir/official'
alias cdexecutor='cd $builder_shared_dir/executor'
alias cdexecutor5='cd $builder_shared_dir/executor5'
alias cdexecutor5bulk='cd $builder_shared_dir/executor5-bulk'
alias cdexecutor5-bulk='cd $builder_shared_dir/executor5-bulk'

alias cdtrunk='cd $builder_src_dir'
alias cdsrc='cd $builder_src_dir'

alias cdconfig='cd $builder_config_dir'
alias cdbuild='cd $builder_build_dir'
alias cddelivery='cd $builder_delivery_dir'

# Title of console
# Note : If you don't see this title, then maybe you have to redefine the variable PS1.
# I had this problem under Ubuntu, where PS1 is defined like that in .bashrc :
# PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u: \w\a\]$PS1"
# By assigning this value to PS1, which does not overwrite the title, I can see *my* title :
# PS1='\w\$ '
# Ubuntu 20 : I have PROMPT_COMMAND=__vte_prompt_command, and that overwrites the title.
# Unset this variable if you have no title.
echo -n -e "\033]0;ooRexx $builder_target $builder_branch $builder_src_relative_path $builder_system_arch $builder_compiler $builder_config\007"

export PATH
export LD_LIBRARY_PATH
export DYLD_LIBRARY_PATH
export C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH
export LIBRARY_PATH
export NLSPATH

# Local scripts, not in Github for the moment
prepend_path PATH "$builder_shared_dir/scripts"

echo "Setting environment for building with ooRexx"
prepend_path C_INCLUDE_PATH "$builder_delivery_dir/include"
prepend_path CPLUS_INCLUDE_PATH "$builder_delivery_dir/include"
prepend_path LIBRARY_PATH "$builder_delivery_dir/lib"

echo "Setting environment for running ooRexx"
prepend_path PATH "$builder_delivery_dir/bin"
prepend_path LD_LIBRARY_PATH "$builder_delivery_dir/lib"
prepend_path DYLD_LIBRARY_PATH "$builder_delivery_dir/lib"
prepend_path NLSPATH "$builder_delivery_dir/bin/rexx.cat"

echo "Setting environment for ooRexx documentation"
export oorexx_doc_dir=$builder_shared_dir/$builder_target/docs
alias cddoc='cd $oorexx_doc_dir'
alias cddocs='cd $oorexx_doc_dir'

echo "Setting environment for ooRexx test framework"
export oorexx_test_trunk=$builder_shared_dir/$builder_target/test/trunk
export oorexx_test_src=$oorexx_test_trunk
prepend_path PATH "$oorexx_test_trunk"
prepend_path PATH "$oorexx_test_trunk/framework"
alias cdtest='cd $oorexx_test_trunk'

################################################################################
# Cross references between ooRexx and executor
################################################################################

# Optional, to do manually if you have installed official ooRexx:
    # From the directory official/incubator, reference some subdirectories in executor :
    # ln -s ../../executor/incubator/ooRexxShell ooRexxShell-executor
    # ln -s ../../executor/incubator/DocMusings DocMusings-executor

    # From the directory official/sandbox, reference some subdirectories in executor :
    # ln -s ../../executor/sandbox/jlf jlf-executor

    # From the directory executor/incubator, reference some subdirectories in official :
    # ln -s ../../official/incubator/ooSQLite ooSQLite
    # ln -s ../../official/incubator/regex regex

################################################################################
# Incubator
################################################################################

echo "Setting environment for incubator"
export oorexx_incubator=$builder_shared_dir/$builder_target/incubator
prepend_path PATH "$oorexx_incubator"
alias cdincubator='cd $oorexx_incubator'

# echo "Setting environment for ooSQLite"
# prepend_path PATH "$oorexx_incubator/ooSQLite/bin/linux"
# prepend_path LD_LIBRARY_PATH "$oorexx_incubator/ooSQLite/bin/linux"
# prepend_path DYLD_LIBRARY_PATH "$oorexx_incubator/ooSQLite/bin/linux"
# alias cdoosqlite='cd $oorexx_incubator/ooSQLite'

################################################################################
# Executor incubator
################################################################################

echo "Setting environment for DocMusings"
if test -z "$executor_docmusings" ; then export executor_docmusings=$oorexx_incubator/docmusings-executor ; fi
if [ ! -d  "$executor_docmusings" ] ; then export executor_docmusings=$oorexx_incubator/docmusings ; fi
alias cddocmusings='cd $executor_docmusings'
export oorexx_transformxml=$executor_docmusings/transformxml
alias cdtransformxml='cd $oorexx_transformxml'
prepend_path PATH "$executor_docmusings"

echo "Setting environment for ooRexxShell"
if test -z "$executor_oorexxshell" ; then export executor_oorexxshell=$oorexx_incubator/ooRexxShell-executor ; fi
if [ ! -d  "$executor_oorexxshell" ] ; then export executor_oorexxshell=$oorexx_incubator/ooRexxShell ; fi
prepend_path PATH "$executor_oorexxshell"
alias cdoorexxshell='cd $executor_oorexxshell'

################################################################################
# Sandbox
################################################################################

echo "Setting environment for the sandbox"
export oorexx_sandbox=$builder_shared_dir/$builder_target/sandbox
alias cdsandbox='cd $oorexx_sandbox'

################################################################################
# Executor sandbox
################################################################################

echo "Setting environment for the sandbox jlf"
if test -z "$executor_sandboxjlf" ; then export executor_sandboxjlf=$oorexx_sandbox/jlf-executor ; fi
if [ ! -d  "$executor_sandboxjlf" ] ; then export executor_sandboxjlf=$oorexx_sandbox/jlf ; fi
prepend_path PATH "$executor_sandboxjlf"
alias cdsandboxjlf='cd $executor_sandboxjlf'
alias cdjlf='cd $executor_sandboxjlf'

echo "Setting environment for the sandbox packages"
export executor_packages=$executor_sandboxjlf/packages
prepend_path PATH "$executor_packages"
alias cdpackages='cd $executor_packages'
alias cdextension='cd $executor_packages/extension'
alias cdextensionstd='cd $executor_packages/extension/std'
alias cdfunctional='cd $executor_packages/functional'
alias cdconcurrency='cd $executor_packages/concurrency'
alias cdmutablebuffer='cd $executor_packages/mutablebuffer'
alias cdrgfutil2='cd $executor_packages/rgf_util2'
alias cdtrace='cd $executor_packages/trace'
alias cdprofiling='cd $executor_packages/profiling'

echo "Setting environment for the sandbox samples"
export executor_samples=$executor_sandboxjlf/samples
prepend_path PATH "$executor_samples"
alias cdsamples='cd $executor_samples'
alias cdextensionsamples='cd $executor_samples/extension'
alias cdextensionstdsamples='cd $executor_samples/extension/std'
alias cdfunctionalsamples='cd $executor_samples/functional'
alias cdconcurrencysamples='cd $executor_samples/concurrency'
alias cdmutablebuffersamples='cd $executor_samples/mutablebuffer'
alias cdrgfutil2samples='cd $executor_samples/rgf_util2'
alias cdtracesamples='cd $executor_samples/trace'

export executor_tests=$executor_sandboxjlf/tests
alias cdtests='cd $executor_tests'

export executor_testx=$builder_shared_dir/executor/testx
alias cdtestx='cd $executor_testx'

export executor_demos=$executor_sandboxjlf/demos
alias cddemos='cd $executor_demos'

export executor_unicode=$executor_sandboxjlf/unicode
alias cdunicode='cd $executor_unicode'
