#!/bin/bash

if [ "$0" = "$BASH_SOURCE" ] ; then echo "Usage : source ${BASH_SOURCE[0]}" ; exit 1 ; fi

# See setenv-clang, setenv-gcc
export builder_profiling=1

# MEMPROFILE activates dumpMemoryProfile in ooRexx
# VERBOSE_GC activates the GC verbose messages
echo "Adding -DMEMPROFILE to activate dumpMemoryProfile"
echo "Adding -DVERBOSE_GC to activate the GC verbose messages"
export CFLAGS="-DMEMPROFILE -DVERBOSE_GC -g -O3 $CFLAGS"
export CXXFLAGS="-DMEMPROFILE -DVERBOSE_GC -g -O3 $CXXFLAGS"

# Cmake has no build type for profiling.
export CMAKE_BUILD_TYPE=RelWithDebInfo
