#!/bin/bash

# NO LONGER USED

# Replaced by
# other_dependencies-oorexx-macos-jlfaucher
# other_dependencies-oorexx-ubuntu-jlfaucher

# Naming convention:
# other_dependencies-oorexx-${builder_system}-${hostname}
# where
#     ${builder_system} is system in <target[.branch]>/d1/d2/.../system/compiler/config/bitness
#     hostname=`hostname -s`
