#!/bin/bash

# File naming convention
# setenv-oorexx-${builder_system_arch}-${hostname}
#               macos-x86_64           jlfaucher-mbp2021

if [ "$0" = "$BASH_SOURCE" ] ; then echo "Usage : source ${BASH_SOURCE[0]}" ; exit 1 ; fi


# load the helpers
. ${builder_scripts_dir}/shellscriptlib
. ${builder_scripts_dir}.private/shellscriptlib-macos


[ -f /local/java/setenv.sh ] && . /local/java/setenv.sh
declare_java

export BSF4OOREXX_HOME=/local/rexx/bsf4oorexx/BSF4ooRexx_install_v641-20220131-ga/bsf4oorexx
export BSF4OOREXX_JAR=bsf4ooRexx-v641-20220131-bin.jar

declare_bsf4oorexx_distribution

#export BSF4OOREXX_HOME=/Local/rexx/bsf4oorexx/svn/trunk
#declare_bsf4oorexx_svn

echo "Setting environment for GCI"
#export GCI_HOME=$builder_shared_dir/../rexx-gci
export GCI_HOME="$( cd -P "$(dirname "$builder_shared_dir")" && pwd )"/rexx-gci
GCI_LIBRARY_PATH=$GCI_HOME/build/$builder_system_arch/$builder_compiler/$builder_config
export DYLD_LIBRARY_PATH
prepend_path DYLD_LIBRARY_PATH "$GCI_LIBRARY_PATH"
alias cdgci='cd $GCI_HOME'

echo "Setting environment for ICU"
. /local/Unicode/ICU/setenv.sh

echo "Setting environment for BOOST"
. /local/cpp/boost/setenv.sh

echo "Setting environment for Dropbox scripts"
prepend_path PATH "~/Dropbox/software/oorexx"

echo "Setting environment for BATIK"
# version 1.13 is not working, version 1.15 is not working... The old version 1.7 is working
# Exception in thread "main" java.lang.NoClassDefFoundError: org/mozilla/javascript/WrapFactory
#export BATIK_ROOT=/local/XmlToolSet/batik-1.15
#export BATIK_RASTERIZER_JAR=$BATIK_ROOT/batik-rasterizer-1.15.jar
export BATIK_ROOT=/local/XmlToolSet/batik-1.7
export BATIK_RASTERIZER_JAR=$BATIK_ROOT/batik-rasterizer.jar

echo "Setting environment for Zig"
. /local/zig/setenv-0.9.1.sh

