#!/bin/bash

# File naming convention
# setenv-${current}-${builder_system_arch}-${builder_hostname}
#        regina     macos-arm64            jlfaucher-mbp2021

if [ "$0" = "$BASH_SOURCE" ] ; then echo "Usage : source ${BASH_SOURCE[0]}" ; exit 1 ; fi


# load the helpers
. $builder_scripts_dir/shellscriptlib


# Nothing for the moment
