#!/bin/bash

# File naming convention
# setenv-${current}-${builder_system_arch}-${builder_hostname}
#        oorexx     ubuntu-x86_64          jlfaucher-mbp2010

if [ "$0" = "$BASH_SOURCE" ] ; then echo "Usage : source ${BASH_SOURCE[0]}" ; exit 1 ; fi


# load the helpers
. ${builder_scripts_dir}/shellscriptlib
. ${builder_scripts_dir}.private/shellscriptlib-linux


[ -f /local/java/setenv.sh ] && . /local/java/setenv.sh
declare_java

# bsf4oorexx version 641 - all platforms
if [ "$builder_target" = "executor" ]
then
    export BSF4OOREXX_HOME=/local/rexx/bsf4oorexx/BSF4ooRexx_install_v641-20220131-ga/bsf4oorexx
    export BSF4OOREXX_JAR=bsf4ooRexx-v641-20220131-bin.jar
    declare_bsf4oorexx_distribution
fi

# bsf4oorexx version 850 - all platforms - can't be used by Executor
if [ "$builder_target" != "executor" ]
then
    export BSF4OOREXX_HOME=/local/rexx/bsf4oorexx/BSF4ooRexx_install_v850-20230718-beta/bsf4oorexx
    export BSF4OOREXX_JAR=bsf4ooRexx-v850-20230718-bin.jar
    declare_bsf4oorexx_distribution
fi

# bsf4oorexx portable (641) - windows only
#export BSF4OOREXX_HOME=/local/rexx/bsf4oorexx/bsf4oorexx_v641.20220131-Darwin-x86_64-portable-UNO-runtime
#export BSF4OOREXX_JAR=bsf4ooRexx-v641-20220131-bin.jar
#declare_bsf4oorexx_distribution

# bsf4oorexx SVN sources
#export BSF4OOREXX_HOME=/Local/rexx/bsf4oorexx/svn/trunk
#declare_bsf4oorexx_svn

echo "Setting environment for ICU"
. /local/Unicode/ICU/setenv.sh

echo "Setting environment for BOOST"
. /local/cpp/boost/setenv.sh

echo "Setting environment for Dropbox scripts"
prepend_path PATH "~/Dropbox/software/oorexx"

echo "Setting environment for BATIK"
# Remember: if v1.13 doesn't work see what has been done for macos
export BATIK_ROOT=/local/XmlToolSet/batik-1.13
export BATIK_RASTERIZER_JAR=$BATIK_ROOT/batik-rasterizer-1.13.jar

#echo "Setting environment for Zig"
#. /local/zig/setenv-0.9.1.sh
