#!/bin/bash

# File naming convention
# setenv-${current}-${builder_system_arch}-${builder_hostname}
#        oorexx     macos-arm64            jlfaucher-mbp2021

if [ "$0" = "$BASH_SOURCE" ] ; then echo "Usage : source ${BASH_SOURCE[0]}" ; exit 1 ; fi


# load the helpers
. ${builder_scripts_dir}/shellscriptlib
. ${builder_scripts_dir}.private/shellscriptlib-macos


# I install a jdk with support for JFX
[ -f /local/java/setenv.sh ] && . /local/java/setenv.sh
declare_java

if [ "$builder_target" = "official" -a "$builder_src_relative_path" = "main/trunk" \
     -o \
     "$builder_target" = "executor5" \
     -o \
     "$builder_target" = "executor5-bulk" ]
then
    # bsf4oorexx version 850 - all platforms - can't be used by Executor
    export BSF4OOREXX_HOME=/local/rexx/bsf4oorexx/BSF4ooRexx_install_v850-20260117-refresh/bsf4oorexx
    export BSF4OOREXX_JAR=bsf4ooRexx-v850-20260117-bin.jar
    declare_bsf4oorexx_distribution
else
    # bsf4oorexx version 641 - all platforms
    export BSF4OOREXX_HOME=/local/rexx/bsf4oorexx/BSF4ooRexx_install_v641-20221002-refresh/bsf4oorexx
    export BSF4OOREXX_JAR=bsf4ooRexx-v641-20221002-bin.jar
    declare_bsf4oorexx_distribution
fi

# bsf4oorexx SVN sources
#export BSF4OOREXX_HOME=/Local/rexx/bsf4oorexx/svn/trunk
#declare_bsf4oorexx_svn

#echo "Setting environment for ICU"
#[ -f /local/Unicode/ICU/setenv.sh ] && . /local/Unicode/ICU/setenv.sh

#echo "Setting environment for BOOST"
#[ -f /local/cpp/boost/setenv.sh ] && . /local/cpp/boost/setenv.sh

echo "Setting environment for Home scripts"
prepend_path PATH "~/software/oorexx"

echo "Setting environment for BATIK"
# version 1.13 is not working, version 1.15 is not working... The old version 1.7 is working
# Exception in thread "main" java.lang.NoClassDefFoundError: org/mozilla/javascript/WrapFactory
# Fixed by adding Rhino in the classpath of MANIFEST.MF in batik-rasterizer-<version>.jar
export BATIK_ROOT=/local/XmlToolSet/batik-1.16
export BATIK_RASTERIZER_JAR=$BATIK_ROOT/batik-rasterizer-1.16.jar

#echo "Setting environment for Zig"
#. /local/zig/setenv-0.9.1.sh

