#!/bin/bash

# $1 is mandatory: debug or profiling or reldbg or release
# $2 is optional: architecture x86_32 or X86_64 or aarch32 or aarch64 (default is the machine hardware)

if [ -z "$BASH_VERSION" ]; then
   echo "Works only with bash"
   return 1
fi

if [ "$0" = "$BASH_SOURCE" ] ; then echo "Usage : source ${BASH_SOURCE[0]}" ; exit 1 ; fi

ARCH="$2"
if test -z "$ARCH"
then
    ARCH=`uname -m`
fi
. ../builder/scripts/setenv /local/rexxlocal/oorexx/build/executor.master/sandbox/jlf/trunk/ubuntu-$ARCH/gcc/$1
